### ISSUE TITLE
Problem of paths in coqui model configs (manual download)

### ISSUE THREAD

**Issue by zhanghuimeng** [thorstenMueller/deep-learning-german-tts#26] opened 2021-08-17 17:12 UTC
Hi there, thank you very much for your contribution! I have succesfully run the TTS by now, but I met a few minor problems before I could finally run it.

As instructed in README, I installed TTS and ran `tts-server --model_name tts_models/de/thorsten/tacotron2-DCA`. Due to GFW or something like that, the models would not download automatically. So I get the models [tts_models/de/thorsten/tacotron2-DCA](https://github.com/coqui-ai/TTS/releases/download/v0.0.11/tts_models--de--thorsten--tacotron2-DCA.zip) and [vocoder_models/de/thorsten/fullband-melga](https://github.com/coqui-ai/TTS/releases/download/v0.0.11/vocoder_models--de--thorsten--wavegrad.zip) from link give by coqui and unzip them to the appropriate place (at least where coqui attempted to place them). After reruning, the program showed error as follows:

```
(venv) PS C:\Users\**mypath**\ThorstenVoice> tts --model_name tts_models/de/thorsten/tacotron2-DCA --text "Was geschehen ist geschehen, es ist geschichte."
 > tts_models/de/thorsten/tacotron2-DCA is already downloaded.
 > vocoder_models/de/thorsten/fullband-melgan is already downloaded.
 > Using model: Tacotron2
Traceback (most recent call last):
  File "c:\users\***\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
    exec(code, run_globals)
  File "C:\Users\**mypath**\ThorstenVoice\venv\Scripts\tts.exe\__main__.py", line 7, 
in <module>
  File "C:\**mypath**\ThorstenVoice\venv\lib\site-packages\TTS\bin\synthesize.py", line 226, in main
    synthesizer = Synthesizer(
  File "C:\Users\**mypath**\ThorstenVoice\venv\lib\site-packages\TTS\utils\synthesizer.py", line 75, in __init__
    self._load_vocoder(vocoder_checkpoint, vocoder_config, use_cuda)
  File "C:\Users\**mypath**\ThorstenVoice\venv\lib\site-packages\TTS\utils\synthesizer.py", line 162, in _load_vocoder
    self.vocoder_ap = AudioProcessor(verbose=False, **self.vocoder_config.audio)
  File "C:\Users\**mypath**\ThorstenVoice\venv\lib\site-packages\TTS\utils\audio.py", line 293, in __init__
    mel_mean, mel_std, linear_mean, linear_std, _ = self.load_stats(stats_path)
  File "C:\Users\**mypath**\ThorstenVoice\venv\lib\site-packages\TTS\utils\audio.py", line 420, in load_stats
    stats = np.load(stats_path, allow_pickle=True).item()  # pylint: disable=unexpected-keyword-arg
  File "C:\Users\**mypath**\ThorstenVoice\venv\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/thorsten/___prj/tts/models/taco2/thorsten-dca/spec-stats.npy'
```

I studied that a bit, and found out that, if I change the `audio.stats_path` property in the config files of the downloaded models (namely `tts/tts_models--de--thorsten--tacotron2-DCA/config.json` and `tts/vocoder_models--de--thorsten--fullband-melgan/config.json`) from something like `/home/erogol/.local/share/tts/tts_models--de--thorsten--tacotron2-DCA/scale_stats.npy` to the appropriate place where `scale_states.npy` really is in my system, the TTS will run smoothly.

I checked both repos' issues, but it seems like no one has reported similiar ones before. I guess the automatic download process will solve the problem, so I just write it down here as a reference for future manual downloaders.

Thank you very much!

**Comment by thorstenMueller** [comment] 2021-08-17 20:17
Thanks for your nice feedback.

> So I get the models tts_models/de/thorsten/tacotron2-DCA and vocoder_models/de/thorsten/fullband-melga from link give by coqui and unzip them to the appropriate place (at least where coqui attempted to place them). After reruning, the program showed error as follows:

The download link you posted is to the wavegrad vocoder model, not to the Fullband-MelGAN model. So maybe that's the cause for the trouble you ran into.

But good to hear you got it working finally :+1:

**Comment by zhanghuimeng** [comment] 2021-08-18 04:57
> The download link you posted is to the wavegrad vocoder model, not to the Fullband-MelGAN model. So maybe that's the cause for the trouble you ran into.

Yeah, I got it 🤦. Thanks! But I noticed that in this repo's README, the Fullband-MelGAN model is still marked as "training-in-progress", while there does exists such a model for download in [coqui release page](https://github.com/coqui-ai/TTS/releases/tag/v0.1.3). I think it would be better to update this infomation?

**Comment by thorstenMueller** [comment] 2021-08-20 04:06
Hi @zhanghuimeng.
> I think it would be better to update this infomation?

Thanks for pointing that out :blush:.
I've updated the README. Closing this issue now, but feel free to reopen it when needed.

**Closed by thorstenMueller** 2021-08-20 04:06 UTC
